# Generated by Django 4.2.5 on 2023-09-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('WIND', 'Eolic'), ('SUN', 'Solar'), ('GEOTHERMAL', 'Geothermal'), ('HYDROGEN', 'Hydrogen')])),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('BATTERY', 'Battery')])),
                ('max_capacity', models.BigIntegerField(default=0)),
                ('current_level', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('HOUSEHOLD', 'Household')])),
                ('grid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.gridaccess')),
                ('producers', models.ManyToManyField(to='core.producer')),
                ('storages', models.ManyToManyField(to='core.storage')),
            ],
        ),
    ]
